export const ADD_TRACKS = "ADD_TRACKS";
export const ADD_FILTER = "ADD_FILTER";
export const FETCH_TRACKS_LOADING = "FETCH_TRACKS_LOADING";
export const FETCH_TRACKS_ERROR = "FETCH_TRACKS_ERROR";
export const FETCH_TRACKS_SUCCESS = "FETCH_TRACKS_SUCCESS";
