export const ADD_FILTER = "ADD_FILTER";
export const FETCH_TRACK_LOADING = "FETCH_TRACKS_LOADING";
export const FETCH_TRACK_ERROR = "FETCH_TRACKS_ERROR";
export const FETCH_TRACK_SUCCESS = "FETCH_TRACKS_SUCCESS";
